In [1]:
import numpy as np

# Theory
Following chapter 7.3 in [Dan Steck's notes](http://atomoptics-nas.uoregon.edu/~dsteck/teaching/quantum-optics/)

Any angular momentum state $|j,m\rangle$ can be rotated by using the Wigner D-matrix
\begin{equation}
R(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'') |j,m\rangle = 
\sum_{m'=-j}^j |j,m'\rangle D_{m',m}^{(j)}(\alpha, \beta, \gamma)
\end{equation}
where the angles $\alpha, \beta, \gamma$ describe the rotation in terms of Euler angles. Note that this is the product of a row vector with a matrix.

The rotation here is decomposed into rotations about the initial $\hat{y}$ and $\hat{z}$ axis and the only non-trivial part of the D-matrix is the rotation about $\hat{y}$, i.e.
\begin{equation}
D_{m',m}^{(j)}(\alpha, \beta, \gamma) = e^{-i m' \alpha} d_{m',m}^{(j)}(\beta\hat{y}) e^{-i m \gamma}
\end{equation}

The wigner small d-matrix is defined as
\begin{equation}
d_{m',m}^{(j)}(\beta\hat{y}) = \langle j,m' |e^{-i J_y / \hbar} |j,m\rangle
\end{equation}
and can be expanded as
\begin{equation}
d_{m',m}^{(j)}(\beta\hat{y}) = 
\sqrt{(j + m)! (j - m)! (j + m')! (j - m')!} \times
\sum_s \frac{(-1)^s}{(j - m' - s)! (j + m - s)! (s + m' - m)! s!}
\left( \cos\left(\frac{\beta}{2}\right) \right)^{2j + m - m' - 2s}
\left( -\sin\left(\frac{\beta}{2}\right)\right)^{m' - m + 2s}.
\end{equation}
where the sum runs over all $s$ for which the factorial is non-negative, i.e. which fulfill
\begin{align}
s &< j - m' \\
s &< j + m \\
s &> m - m' \\
s &> 0
\end{align}
Note that the in the definition on [Wikipedia](https://en.wikipedia.org/wiki/Wigner_D-matrix#cite_note-1) the (-1) from the sine term is pulled into the sum. 

If we want to rotate a polarization vector defined in sperical coorinates with basis
\begin{align}
\hat{e}_{\pm 1} &= \mp\left(\hat{x} \pm i \hat{y}\right) \equiv \sigma_{\pm}\\
\hat{e}_0 &= \hat{z} \equiv \pi
\end{align}
we have to calculate the Wigner D-matrix for $j=1$
\begin{equation}
d_{m',m}^{(1)}(\theta\hat{y}) = 
\begin{pmatrix}
\frac{1}{2}(1 + \cos\theta) & -\frac{1}{\sqrt{2}}\sin\theta & \frac{1}{2}(1 - \cos\theta) \\
\frac{1}{\sqrt{2}}\sin\theta & \cos\theta &  -\frac{1}{\sqrt{2}}\sin\theta \\
\frac{1}{2}(1 - \cos\theta) & \frac{1}{\sqrt{2}}\sin\theta & \frac{1}{2}(1 + \cos\theta)
\end{pmatrix}
\end{equation}

And arbitrary rotations are given by (see also [1])
\begin{equation}
R(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'') = 
D_{m',m}^{(1)}(\alpha, \beta, \gamma) = e^{-i m' \alpha} d_{m',m}^{(1)}(\beta\hat{y}) e^{-i m \gamma} =
\begin{pmatrix}
\frac{1}{2}(1 + \cos\beta) e^{i (\alpha + \gamma)} & 
-\frac{1}{\sqrt{2}}\sin\beta e^{i \alpha } & 
\frac{1}{2}(1 - \cos\beta) e^{i (\alpha - \gamma)}\\
\frac{1}{\sqrt{2}}\sin\beta e^{i \gamma}& 
\cos\beta &  
-\frac{1}{\sqrt{2}}\sin\beta e^{-i \gamma} \\
\frac{1}{2}(1 - \cos\beta) e^{-i (\alpha - \gamma)} & 
\frac{1}{\sqrt{2}}\sin\beta e^{-i \alpha}& 
\frac{1}{2}(1 + \cos\beta) e^{-i (\alpha + \gamma)}
\end{pmatrix}
\end{equation}

**Interesting side note**: For $j=1/2$ the exponentials in $R$ are not $2\pi$-periodic anymore. For this reason a qubit picks up a negative phase when rotated by only $2\pi$. 

So far we calculated what a state $|j,m\rangle$ looks like when we rotate it about $\zeta = \alpha\hat{z} + \beta\hat{y}' + \gamma\hat{z}''$ ([2] calls those active rotations). If we want to know how the same vector is represented in a rotated coodinate system we have to use the inverse  of the rotation ([2] calls those passive), i.e. 
\begin{equation}
R^{(p)}(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'') = R^\mathrm{(a) \dagger}(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'')
\end{equation}
We can calculate the matrix elements of the passive roation
\begin{equation}
\langle j,m'| R^{(p)}(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'') |j,m\rangle = 
\langle j,m'| R^{(a)\dagger}(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'') |j,m\rangle = 
\left(\langle j,m| R^{(a)}(\alpha\hat{z}, \beta\hat{y}', \gamma\hat{z}'') |j,m'\rangle\right)^* =
D_{m,m'}^{(j)*}(\alpha,\beta,\gamma)
\end{equation}
Therefore the same vector in a **rotated coodinate system** is given by
\begin{equation}
|j, m\rangle'= 
\sum_{m'} |j m'\rangle D_{m',m}^{(j) (p)}(\alpha,\beta,\gamma)
\sum_{m'} |j m'\rangle D_{m,m'}^{(j)*}(\alpha,\beta,\gamma)
\end{equation}
This is now the product of the complex conjugated D-matrix with a row vector.

[1] J.D. Louck, *Angular momentum theory*, in Atomic, molecular and optical physics handbook.

[2] M. A. Morrison and G. A. Parker, *A Guide to Roations in Quantum Mechanics*, Aust. J. Phys., **40**, 465-497 (1987).

# Calculate d-matrix elements

In [2]:
def s_sum(j, m, mp, s_min, s_max):
    """Calculate the sum term in small d. """
    
    res = []
    for s in np.arange(s_min, s_max + 1, 1):
        t1 = (-1)**int(s) / \
            (np.math.factorial(j - mp - s) * \
             np.math.factorial(j + m - s) * \
             np.math.factorial(s + mp - m) * \
             np.math.factorial(s))
        t2 = 2*j + m - mp - 2*s                    # exponent of cosine term
        t3 = mp - m + 2*s                          # exponent of sine term
        res.append((t1, t2, t3))
    return res

def root(j, m, mp):
    """Calculate the square root term in small d. """
    return np.sqrt(np.math.factorial(j+m) * np.math.factorial(j-m) * np.math.factorial(j+mp) * np.math.factorial(j-mp))

In [3]:
m = 1
mp = 0
j = 1
t1 = root(j, m, mp)
t2 = s_sum(j, m, mp, 1, 1)


print(t1)
print(t2)

1.4142135623730951
[(-1.0, 1, 1)]


In [4]:
def R_naive(a, b, g):
    c = np.cos(b/2)
    s = np.sin(b/2)
    
    ac = 1j * a
    gc = 1j * g
    
    return np.matrix([[c**2 * np.exp(ac) * np.exp(gc), -np.sqrt(2) * s * c * np.exp(ac), s**2 * np.exp(ac) * np.exp(-gc)],
                     [np.sqrt(2) * s * c * np.exp(gc), 1 - 2*s**2, -np.sqrt(2) * s * c * np.exp(-gc)],
                     [s**2 * np.exp(-ac) * np.exp(gc), np.sqrt(2) * s * c * np.exp(-ac), c**2 * np.exp(-ac) * np.exp(-gc)]])

def R(a, b, g):   
    return np.matrix(
        [[(1+np.cos(b))/2 * np.exp(1j*(a+g)), -np.sin(b)/np.sqrt(2) * np.exp(1j*a), (1-np.cos(b))/2 * np.exp(1j*(a-g))],
         [np.sin(b)/np.sqrt(2) * np.exp(1j*g), np.cos(b), -np.sin(b)/np.sqrt(2) * np.exp(-1j*g)],
         [(1-np.cos(b))/2 * np.exp(-1j*(a-g)), np.sin(b)/np.sqrt(2) * np.exp(-1j*a), (1+np.cos(b))/2 * np.exp(-1j*(a+g))]]
    )

def dmpm(b):
    return np.matrix(
        [[(1+np.cos(b))/2, -np.sin(b)/np.sqrt(2), (1-np.cos(b))/2],
         [np.sin(b)/np.sqrt(2), np.cos(b), -np.sin(b)/np.sqrt(2)],
         [(1-np.cos(b))/2, np.sin(b)/np.sqrt(2), (1+np.cos(b))/2]]
    )

## Example 1

A rotation by $(\alpha = 0, \beta=\pi, \gamma = 0)$ (i.e. the transformation $\hat{x}\rightarrow -\hat{x}, \hat{z}\rightarrow -\hat{z}$) results in 
\begin{align}
\hat{e}_{\pm 1} &\rightarrow \hat{e}_{\mp 1} \\
\hat{e}_0 &\rightarrow -\hat{e}_0
\end{align}

In [5]:
np.round(R(0, np.pi, 0).conj(), 4)

matrix([[ 0.-0.j, -0.-0.j,  1.-0.j],
        [ 0.-0.j, -1.-0.j, -0.-0.j],
        [ 1.-0.j,  0.-0.j,  0.-0.j]])

**Note**: The rows of the rotation matrix correspond to the transformation of the basis vectors because $\hat{e}_q' = \sum_\mu D^*_{q,\mu}\hat{e}_\mu$ where we can write the basis vectors in the spherical basis as
\begin{align}
\hat{e}_{-1} &\equiv \begin{pmatrix}1&0&0\end{pmatrix}^T \\
\hat{e}_{0} &\equiv \begin{pmatrix}0&1&0\end{pmatrix}^T\\
\hat{e}_{1} &\equiv \begin{pmatrix}0&0&1\end{pmatrix}^T
\end{align}

## Example 2

A rotation by $(\alpha = 0, \beta=\pi/2, \gamma = 0)$ (i.e. the transformation $\hat{x}\rightarrow -\hat{z}, \hat{z}\rightarrow \hat{x}$) results in 
\begin{align}
\hat{e}_{-1} &\rightarrow \frac{1}{2} \left(\hat{e}_{-1} - \sqrt{2}\hat{e}_0 + \hat{e}_1\right) \\
\hat{e}_0 &\rightarrow \frac{1}{\sqrt{2}} \left(\hat{e}_{-1} - \hat{e}_1\right) \\
\hat{e}_1 &\rightarrow \frac{1}{2} \left(\hat{e}_{-1} + \sqrt{2}\hat{e}_0 + \hat{e}_1\right)
\end{align}

In [6]:
np.round(R(0, np.pi/2, 0).conj(), 4)

matrix([[ 0.5   -0.j, -0.7071-0.j,  0.5   -0.j],
        [ 0.7071-0.j,  0.    -0.j, -0.7071-0.j],
        [ 0.5   -0.j,  0.7071-0.j,  0.5   -0.j]])

# Transforming polarization between different quantization axes

Let's consider the case where we know the polarization of light in carthesian coordinates (i.e. with respect to the quantization axis $\hat{z}$) and we want to know what polarization an atom with a different quantization axis $\hat{z}'$ sees. What we have to do now is the following
1. Express the polarization in the $\hat{e}_0, \hat{e}_{\pm 1}$ basis, i.e. with a quantization axis along $\hat{z}$.
2. Transform to the coordinate system with rotated quantization axis.

For the first step we either need to have pure $\pi$ or $\sigma_\pm$ polarization or otherwise find the representation of the polarization in spherical coordinates. We will use the standard decomposition into spherical coodintates, i.e.
\begin{equation}
{\bf A} = \sum_{q=-1}^1 A_q \hat{e}_{q}^* = \sum_{q=-1}^1 (-1)^q A_q \hat{e}_{-q}
\end{equation}
In order to find the coefficients $A_q$ we need to solve 
\begin{equation}
-A_{-1}\hat{e}_{1} + A_0 \hat{e}_0 - A_1 \hat{e}_{-1} = A_x\hat{x} + A_y\hat{y} + A_z\hat{z}
\end{equation}
which can be rewritten as
\begin{align}
-\frac{1}{\sqrt{2}} (A_1 - A_{-1}) &= A_x \\
\frac{i}{\sqrt{2}} (A_1 + A_{-1}) &= A_y \\
A_0 &= A_z.
\end{align}
Solving for the coefficients $A_q$ then yields
\begin{align}
A_{-1} &= \frac{1}{\sqrt{2}} (A_x - i A_y) \\
A_0 &= A_z \\
A_1 &= -\frac{1}{\sqrt{2}} (A_x +i A_y).
\end{align}

Next we need to rotate to the new quantization axis $\hat{z}'$. If we can write the new quantization axis in our old reference frame as $\hat{z}' = n_x \hat{x} + n_y \hat{y} + n_z\hat{z}$ then we just have to apply the rotation 
\begin{equation}
p' = R^*(0, \theta, \phi) 
\begin{pmatrix}
-A_{1} \\ A_0 \\ -A_{-1}
\end{pmatrix}
\end{equation}
where the angles $\theta$ and $\phi$ are given by
\begin{align}
\theta &= \arccos (n_z) \\ 
\phi &= \arctan \left( \frac{n_y}{n_x} \right)
\end{align}

**Note** that we implicitly assumed that all vectors are normalized to unity.

In [7]:
def x_to_sp(vec):
    Am = (vec[0] - 1j * vec[1]) / np.sqrt(2)
    A0 = vec[2]
    Ap = - (vec[0] + 1j * vec[1]) / np.sqrt(2)
    return np.array([-Ap, A0, -Am])

def sp_to_x(vec):
    Am = -vec[2]; A0 = vec[1]; Ap = -vec[0]
    Ax = -(Ap - Am) / np.sqrt(2)
    Ay = 1j * (Ap + Am) / np.sqrt(2)
    Az = A0
    return np.array([Ax, Ay, Az])

## Example 3
Let's consider the case where we have light polarized as $p = (\hat{x} + \hat{y}) / \sqrt{2}$. In terms of $\hat{e}_0, \hat{e}_{\pm 1}$ that is $p_z = \frac{1+i}{2}\hat{e}_{-1} - \frac{1-i}{2}\hat{e}_1$

In [8]:
# axis of polarization
pol = np.array([1, 1, 0]) / np.sqrt(2)

# polarization in spherical coordinates
Am = (pol[0] - 1j * pol[1]) / np.sqrt(2)
A0 = pol[2]
Ap = -(pol[0] + 1j * pol[1]) / np.sqrt(2)

pol_z = np.array([-Ap, A0, -Am])

print(pol_z)

[ 0.5+0.5j  0. +0.j  -0.5+0.5j]


If we want to know what polarization an atom sees which has a quantization axis along $\hat{z}' = (\hat{x}+\hat{y})/\sqrt{2}$ we need to rotate by $\theta = \pi/2$, $\phi = \pi/4$ and should get, that the atom just sees lineraly polarized light.

In [9]:
# quantization axis in carthesian coordinates
quant = np.array([1, 1, 0]) / np.sqrt(2)

theta = np.arccos(quant[2])
phi = np.arctan2(quant[1], quant[0])

pol_prime = np.dot(R(0, theta, phi).conj(), pol_z).T

print(np.round(pol_prime, 4))

[[ 0.+0.j]
 [ 1.+0.j]
 [-0.+0.j]]


## Alternative approach

Alternative to the above approach we could also get to the same result by applying two consecutive rotations if we have a known superposition of $\pi$ and $\sigma_\pm$ polarization along one particular quantization axis $\hat{z}_p = n_{x,p} \hat{x} + n_{y,p} \hat{y} + n_{z,p}\hat{z}$.

In this case we can write the basis vector $\hat{p} = -A_1\hat{e}_{-1} + A_0\hat{e}_0 - A_{-1}\hat{e}_1$. Then we rotate it to the usual frame with quantization axis along $\hat{z}$. This means we have to apply the inverse rotation of the one we defined for transforming between coordinate systems, i.e.
\begin{equation}
p_\hat{z} = 
\begin{pmatrix}
-A_+ & A_0 & -A_-
\end{pmatrix} \cdot
R(0,\theta_p, \phi_p) \cdot
\end{equation}
where the angles are given by $\theta_p = \arccos (n_{z,p})$ and $\phi_p = \arctan \left( \frac{n_{y,p}}{n_{x,p}} \right)$. Note that we have to use the negative angles to get the transformation from the coordinate system $\hat{z}_p$ to $\hat{z}$.

Afterwards we apply the same rotations as above, i.e.
\begin{equation}
p' = 
R^*(0,\theta, \phi) \cdot p_\hat{z}^T = 
R^*(0,\theta, \phi) R^T(0,\theta_p, \phi_p)
\begin{pmatrix}
-A_1 \\ A_0 \\ -A_{-1}
\end{pmatrix}
\end{equation}
**Note** that it is not possible to write the multiplication of two rotations as one rotation with the sum of the angles since we rotate about different axes (it only works when we only rotate once about the $\hat{z}$ axis, i.e. $\theta = 0$).

## Exampe 4
With the same numbers as above

In [10]:
# axis along we know the polarization
z_p = np.array([1, 1, 0]) / np.sqrt(2)
# polarization along z_p
pol_p = np.array([0, 1, 0])
# desired quantization axis
quant = np.array([1, 1, 0]) / np.sqrt(2)

theta_p = np.arccos(z_p[2])
phi_p = np.arctan2(z_p[1], z_p[0])

theta = np.arccos(quant[2])
phi = np.arctan2(quant[1], quant[0])

pol_z = np.dot(pol_p, R(0, theta_p, phi_p))

pol_prime = np.dot(np.dot(R(0, theta, phi).conj(),R(0, theta_p, phi_p).T), pol_p)

print(np.round(pol_z, 4))
print(np.round(pol_prime, 4))

[[ 0.5+0.5j  0. +0.j  -0.5+0.5j]]
[[0.-0.j 1.+0.j 0.-0.j]]


## Example 5
What polarization does an atom quantized along $\hat{z}$ see when $\sigma_+$ polarized light propagates along $\hat{x}$?

In [11]:
pol = np.array([0,0,1]) # sigma+
pol_axis = np.array([1,0, 0])
quant_axis = np.array([0, 0, 1])

theta = np.arccos(pol_axis[2])
phi = np.arctan2(pol_axis[1], pol_axis[0])
pol_z = np.dot(pol, R(0, theta, phi))
print(pol_z)

[[0.5       +0.j 0.70710678+0.j 0.5       +0.j]]


In [12]:
print('Ax = {:.2f}'.format(-1/np.sqrt(2) * (pol_z[0,2]-pol_z[0,0])))
print('Ay = {:.2f}'.format(1j/np.sqrt(2) * (pol_z[0,2]+pol_z[0,0])))
print('Az = {:.2f}'.format(pol_z[0,1]))

Ax = -0.00+0.00j
Ay = 0.00+0.71j
Az = 0.71+0.00j


$\sigma_+^{(\hat{z})}$

In [13]:
sigma_p_z = [-1/np.sqrt(2), -1j / np.sqrt(2), 0] # -1/sqrt(2) * (x + iy)
sigma_p_sp = x_to_sp(sigma_p_z) # (0, 0, 1)
print(sigma_p_sp[0], sigma_p_sp[1], sigma_p_sp[2])

-0j 0j (0.9999999999999998-0j)


$\sigma_-^{(\hat{z})}$

In [14]:
sigma_m_z = [1/np.sqrt(2), -1j / np.sqrt(2), 0] # 1/sqrt(2) * (x - iy)
sigma_m_sp = x_to_sp(sigma_m_z) # (1, 0 , 0)
print(sigma_m_sp[0], sigma_m_sp[1], sigma_m_sp[2])

(0.9999999999999998-0j) 0j (-0-0j)


$\sigma_+^{(\hat{x})}$

In [15]:
sigma_p_x = [0, -1/np.sqrt(2), -1j / np.sqrt(2)] # -1/sqrt(2) * (y + iz)
sigma_p_sp = x_to_sp(sigma_p_x)
print(sigma_p_sp)

pol = np.array([0,0,1]) # sigma+
pol_axis = np.array([1,0, 0]) # x basis
quant_axis = np.array([0, 0, 1])

theta = np.arccos(pol_axis[2])
phi = np.arctan2(pol_axis[1], pol_axis[0])
pol_z = np.dot(pol, R(0, theta, phi))
print(pol_z[0,:] * (-1j)) # global phase of exp(-i * pi/2)

print(sigma_p_sp[0], sigma_p_sp[1], sigma_p_sp[2])

[-0.-0.5j        -0.-0.70710678j -0.-0.5j       ]
[[0.-0.5j        0.-0.70710678j 0.-0.5j       ]]
(-0-0.49999999999999994j) (-0-0.7071067811865475j) (-0-0.49999999999999994j)


$\sigma_-^{(\hat{x})}$

In [16]:
sigma_m_x = [0, 1/np.sqrt(2), -1j / np.sqrt(2)] # 1/sqrt(2) * (y - iz)
sigma_m_sp = x_to_sp(sigma_m_x)
print(sigma_m_sp)

pol = np.array([1,0,0]) # sigma-
pol_axis = np.array([1,0, 0]) # x basis
quant_axis = np.array([0, 0, 1])

theta = np.arccos(pol_axis[2])
phi = np.arctan2(pol_axis[1], pol_axis[0])
pol_z = np.dot(pol, R(0, theta, phi))
print(pol_z[0,:] * 1j) # global phase of exp(-i * 3*pi/2)

print(sigma_m_sp[0], sigma_m_sp[1], sigma_m_sp[2])

[ 0.+0.5j        -0.-0.70710678j -0.+0.5j       ]
[[0.+0.5j        0.-0.70710678j 0.+0.5j       ]]
0.49999999999999994j (-0-0.7071067811865475j) (-0+0.49999999999999994j)


$\sigma_+^{(\hat{y})}$

In [17]:
sigma_p_y = [-1j / np.sqrt(2), 0, -1/np.sqrt(2)] # -1/sqrt(2) * (z + ix)
sigma_p_sp = x_to_sp(sigma_p_y)
print(sigma_p_sp)

pol = np.array([0,0,1]) # sigma+
pol_axis = np.array([0,1, 0]) # y basis
quant_axis = np.array([0, 0, 1])

theta = np.arccos(pol_axis[2])
phi = np.arctan2(pol_axis[1], pol_axis[0])
pol_z = np.dot(pol, R(0, theta, phi))
print(np.round(pol_z[0,:], 10)) # global phase of exp(-i * pi)

print(sigma_p_sp[0], sigma_p_sp[1], sigma_p_sp[2])

[-0.        -0.5j -0.70710678+0.j   0.        +0.5j]
[[0.        +0.5j 0.70710678+0.j  0.        -0.5j]]
(-0-0.49999999999999994j) (-0.7071067811865475+0j) 0.49999999999999994j


$\sigma_-^{(\hat{y})}$

In [18]:
sigma_m_y = [-1j / np.sqrt(2), 0, 1/np.sqrt(2)] # 1/sqrt(2) * (z - ix)
sigma_m_sp = x_to_sp(sigma_m_y) 
print(sigma_m_sp)

pol = np.array([1,0,0]) # sigma-
pol_axis = np.array([0,1, 0]) # y basis
quant_axis = np.array([0, 0, 1])

theta = np.arccos(pol_axis[2])
phi = np.arctan2(pol_axis[1], pol_axis[0])
pol_z = np.dot(pol, R(0, theta, phi))
print(np.round(pol_z[0,:], 10)) # global phase of exp(-i * pi)

print(sigma_m_sp[0], sigma_m_sp[1], sigma_m_sp[2])

[-0.        -0.5j  0.70710678+0.j   0.        +0.5j]
[[ 0.        +0.5j -0.70710678+0.j   0.        -0.5j]]
(-0-0.49999999999999994j) (0.7071067811865475+0j) 0.49999999999999994j


In [19]:
p = [-0.5j, 1 / np.sqrt(2), 0.5j] # 1 / sqrt(2) * (z - ix)
sp_to_x(p)

p = [-0.5j, -1 / np.sqrt(2), 0.5j] # - 1/sqrt(2) * (z + ix)
sp_to_x(p)

array([-0.        -0.70710678j,  0.        +0.j        ,
       -0.70710678+0.j        ])

# Rotate a vector

In [20]:
def Rx(theta):
    return np.array([[1, 0, 0],
                     [0, np.cos(theta), -np.sin(theta)],
                     [0, np.sin(theta), np.cos(theta)]])

def Ry(theta):
    return np.array([[np.cos(theta), 0, np.sin(theta)],
                     [0, 1, 0],
                     [-np.sin(theta), 0, np.cos(theta)]])

def Rz(theta):
    return np.array([[np.cos(theta), -np.sin(theta), 0],
                     [np.sin(theta), np.cos(theta), 0],
                     [0,0,1]])

In [21]:
beta = 45 * np.pi / 180
nz = np.array([np.cos(beta),0,np.sin(beta)])
nz = nz / np.sqrt(np.sum(nz**2))

phi = np.arctan2(nz[1], nz[0]) 
theta = np.arccos(nz[2])
alpha = 0 * np.pi / 180

#gamma = 0 * np.pi / 180
#beta = 45 * np.pi / 180
#gamma = 0 * np.pi / 180

# align x axis
R1 = Rz(alpha)
R2 = Ry(theta)#np.dot(R1.T, np.dot(Ry(theta), R1))

# align y&z axis
R3 = Rz(phi)#np.dot(R2, np.dot(Rz(phi), R2.T))

R_tot = np.dot(R3, np.dot(R2, R1))

In [22]:
print(np.round(np.dot(R_tot, np.array([1,0,0])), 4))
print(np.round(np.dot(R_tot, np.array([0,1,0])), 4))
print(np.round(np.dot(R_tot, np.array([0,0,1])), 4))

[ 0.7071  0.     -0.7071]
[0. 1. 0.]
[0.7071 0.     0.7071]


In [23]:
print(theta, phi)

0.7853981633974484 0.0


In [24]:
beta = 45 * np.pi / 180
nz = np.array([np.cos(beta),0,np.sin(beta)])